In [2]:
import pandas as pd

print(pd.__version__)
expenses = pd.read_csv("D:/Projects/Personal Expense Intelligence/data/raw/myExpenses1.csv")

2.3.3

In [3]:
expenses.shape
expenses.head()

         Date     Item  Amount Category   Time        day
0  01-03-2023     chai       7    alone  07:00  Wednesday
1  01-03-2023     chai      20   friend  10:00  Wednesday
2  01-03-2023    juice      15   friend  13:00  Wednesday
3  01-03-2023  rikshow      12    alone  14:00  Wednesday
4  01-03-2023   coffee      12    alone  15:00  Wednesday

In [4]:
expenses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      145 non-null    object
 1   Item      145 non-null    object
 2   Amount    145 non-null    int64
 3   Category  144 non-null    object
 4   Time      145 non-null    object
 5   day       145 non-null    object
dtypes: int64(1), object(5)
memory usage: 6.9+ KB

In [5]:
expenses[expenses["Category"].isna()]
expenses.loc[68:76]

          Date      Item  Amount Category   Time     day
68  12-03-2023  coldrink      20   friend  14:10  Sunday
69  12-03-2023      chai      10   friend  18:00  Sunday
70  12-03-2023  recharge     210    alone  12:00  Sunday
71  12-03-2023  coldrink      10   friend  21:00  Sunday
72  12-03-2023    others      10      NaN  18:30  Sunday
73  13-03-2023      chai      10    alone  07:00  Monday
74  13-03-2023    petrol      70   friend  10:00  Monday
75  13-03-2023     juice      25   friend  11:00  Monday
76  13-03-2023    coffee      12    alone  17:00  Monday

In [6]:
expenses["Category"].value_counts(dropna=False)

Category
alone     91
friend    53
NaN        1
Name: count, dtype: int64

In [7]:
expenses["Amount"].describe()

count    145.000000
mean      31.786207
std       56.389541
min        5.000000
25%       12.000000
50%       17.000000
75%       30.000000
max      500.000000
Name: Amount, dtype: float64

In [8]:
expenses.loc[expenses["Amount"].idxmax()]

Date        05-03-2023
Item              shoe
Amount             500
Category         alone
Time             17:30
day             Sunday
Name: 32, dtype: object

In [9]:
expenses["Item"].value_counts()

Item
chai with snaks    48
chai               21
others             16
coldrink           11
coffee             10
juice               9
rikshow             4
biryani             4
idli                3
chicken             3
samosa              3
ice cream           2
shoe                1
chiness bhel        1
choclate            1
pizza               1
chass               1
faluda              1
wifi                1
recharge            1
petrol              1
freanky             1
maggi               1
Name: count, dtype: int64

In [ ]:
expenses["Date"].head(10)

31

In [21]:
expenses["Date"].nunique()
expenses[["Date", "day"]].head(10)

        Date        day
0 2023-03-01  Wednesday
1 2023-03-01  Wednesday
2 2023-03-01  Wednesday
3 2023-03-01  Wednesday
4 2023-03-01  Wednesday
5 2023-03-01  Wednesday
6 2023-03-01  Wednesday
7 2023-03-01  Wednesday
8 2023-03-02   Thursday
9 2023-03-02   Thursday